export const SUCCESS_REGISTER = 'SUCCESS_REGISTER'
export const REGISTER_VERIFICATION = 'REGISTER_VERIFICATION'
export const SUCCESS_LOGIN = 'SUCCESS_LOGIN'
export const LOG_OUT = 'LOG_OUT'
export const LOAD_USER =' LOAD_USER'
export const DELETE_USER = 'DELETE_USER'
export const UPDATE_USER = 'UPDATE_USER'
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD'
export const LOGOUT = 'LOGOUT'
export const FORGOT_REQUEST = 'FORGOT_REQUEST'
export const RESET_PASSWORD = 'RESET_PASSWORD'


export const CLEAR_ERROR = 'CLEAR_ERROR'
export const ERROR = 'ERROR'
export const EDIT_FORM = 'EDIT_FORM'
export const CLEAR_EDIT_FORM = 'CLEAR_EDIT_FORM'
export const CLEAR_SUCCESS = 'CLEAR_SUCCESS'




export const GET_PRODUCT= 'GET_PRODUCT'
export const UPLOAD_PRODUCT= 'UPLOAD_PRODUCT'
export const UPDATE_PRODUCT= 'UPDATE_PRODUCT'
export const DELETE_PRODUCT= 'DELETE_PRODUCT'

export const GET_CUSTOMERS = 'GET_CUSTOMERS'
export const GET_CUSTOMER = 'GET_CUSTOMER'
export const CREATE_CUSTOMER= 'CREATE_CUSTOMER'
export const UPDATE_CUSTOMER= 'UPDATE_CUSTOMER'
export const DELETE_CUSTOMER= 'DELETE_CUSTOMER'
export const GET_INVOICE = 'GET_INVOICE'
export const PAY_DUE = 'PAY_DUE'

export const CREATE_INVOICE = 'CREATE_INVOICE'
export const GET_INVOICES = 'GET_INVOICES'
export const DELETE_INVOICE= 'DELETE_INVOICE'

export const GET_INVOICE_PRODUCT= 'GET_INVOICE_PRODUCT'
export const GET_INVOICE_CUSTOMER = 'GET_INVOICE_CUSTOMER'
export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'

export const GET_PRODUCT_INFO = 'GET_PRODUCT_INFO'
export const GET_SALE_INFO = 'GET_SALE_INFO'
export const GET_TOTAL_CUSTOMER = 'GET_TOTAL_CUSTOMER'
export const GET_RECENT_SALE = 'GET_RECENT_SALE'
export const GET_SALE_INFO_BY_DAY = 'GET_SALE_INFO_BY_DAY'
export const GET_TODAY_SALE = 'GET_TODAY_SALE'

export const CLEAR_APPLICATION_STATE = 'CLEAR_APPLICATION_STATE'


export const GET_CATEGORY = 'GET_CATEGORY'
export const ADD_CATEGORY = 'ADD_CATEGORY'
export const DELETE_CATEGORY = 'DELETE_CATEGORY'
export const ADD_SUB_CATEGORY = 'ADD_SUB_CATEGORY'
export const DELETE_SUB_CATEGORY = 'DELETE_SUB_CATEGORY'




export const GET_ORDERS = 'GET_ORDERS'
export const GET_SINGLE_ORDER = 'GET_SINGLE_ORDER'
export const CHANGE_ORDER_STATUS = 'CHANGE_ORDER_STATUS'
export const ADD_TO_CART = 'ADD_TO_CART'







